version: '3.7'

services:

  db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_DB=dbInvControlDEV
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
